# Generated by Django 4.2.2 on 2023-06-20 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='brand',
            new_name='band_en',
        ),
        migrations.AddField(
            model_name='clothe',
            name='brand_kr',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
    ]
