# Generated by Django 4.2.2 on 2023-06-20 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0002_rename_brand_clothe_band_en_clothe_brand_kr'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clothe',
            old_name='band_en',
            new_name='brand',
        ),
        migrations.RemoveField(
            model_name='clothe',
            name='brand_kr',
        ),
    ]
